# http://docs.travis-ci.com/user/build-configuration/

language: php

os: linux

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4


  install: skip
  
  script: skip
  
  notifications:
    email: false
  
  before_deploy:
    - wget https://github.com/boxbilling/boxbilling/releases/latest/download/BoxBilling.zip
    - unzip Boxbilling.zip -d boxbilling
    - cp -r ./src/bb-config-heroku.php ./boxbilling/bb-config.php
    - cp -r ./boxbilling/htaccess.txt ./boxbilling/.htaccess
    - rm -rf ./boxbilling/install
    - rm -rf ./boxbilling/htaccess.txt
    - rm -rf ./boxbilling/bb-config-sample.php
    - rm -rf BoxBilling.zip
  
  deploy:
    provider: heroku
    api_key: $HEROKU_AUTH_TOKEN
    app: boxbilling-demo
    skip_cleanup: true
    file_glob: true
    file: boxbilling/* 
    run:
      - php bin/prepare.php
  
  branches:
  only:
    - dev/heroku    