# http://docs.travis-ci.com/user/build-configuration/

language: php

os: linux

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4
  
before_install:
  - chmod +x ./bin/heroku.sh
install: skip

script: skip

notifications:
  email: false

before_deploy:
  - ./bin/heroku.sh

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: boxbilling-demo
  skip_cleanup: true
  file_glob: true
  file: boxbilling/* 
  run:
    - php bin/prepare.php