{% extends "layout_default.phtml" %}

{% block meta_title %}{% trans 'Error' %}{% endblock %}

{% block content_before %}
        <!-- Page Heading/Breadcrumbs -->        
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">404</h1>
				<ol class="breadcrumb">
                    <li class="breadcrumb-item"><a class="text-decoration-none" href="{{''|link}}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">404</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}

<div class="col">
    <div class="h-100 p-5 bg-light border rounded-3 shadow">
        <h1>{% trans 'Looks like we have a misunderstanding here' %}</h1>
	    <p>{{ exception.getMessage }}</p>
    </div>
</div>

{% endblock %}