{% set company = guest.system_company %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block meta_title %}{% endblock %} {{ settings.meta_title }}</title>

    <meta property="bb:url" content="{{ constant('BB_URL') }}" />
    <meta property="bb:client_area" content="{{ '/'|link }}" />

    <meta name="description" content="{% block meta_description %}{{ settings.meta_description }}{% endblock %}" />
    <meta name="keywords" content="{% block meta_keywords %}{{ settings.meta_keywords }}{% endblock %}" />
    <meta name="robots" content="{% if settings.meta_robots|default %}{{ settings.meta_robots }}{% else %}index, follow{% endif %}" />
    <meta name="author" content="{{ settings.meta_author }}">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <link rel="shortcut icon" href="{{ 'favicon.ico' | asset_url }}" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ 'css/bootstrap.min.css' | asset_url }}">

    <!-- Bootstrap Markdown Editor -->
    <link href="{{ 'css/bootstrap-markdown.min.css' | asset_url }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ 'css/style.css' | asset_url }}" rel="stylesheet"> {% if settings.inject_css|default %}
    <!-- Custom CSS -->
    <style>
        {{ settings.inject_css|raw }}
    </style>
    {% endif %}

    <!-- Font Awesome -->
    <link href="{{ 'font-awesome/css/fontawesome.min.css' | asset_url }}" rel="stylesheet" type="text/css">
    <link href="{{ 'font-awesome/css/solid.min.css' | asset_url }}" rel="stylesheet" type="text/css">

    <!-- jQuery -->
    <script src="{{ 'js/jquery.min.js' | asset_url }}"></script>

    <!-- BoxBilling jQuery -->
    <script src="{{ 'js/bb-jquery.js' | asset_url }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ 'js/bootstrap.bundle.min.js' | asset_url }}"></script>

    <!-- Bootstrap Markdown Editor -->
    <script src="{{ 'js/bootstrap-markdown.js' | asset_url }}"></script>
    <script src="{{ 'js/to-markdown.js' | asset_url }}"></script>
    <script src="{{ 'js/markdown.js' | asset_url }}"></script>

    {% if settings.inject_javascript|default %}
    <!-- Custom JavaScript -->
    <script>
        {{ settings.inject_javascript|raw }}
    </script>
    {% endif %} {% block js %}{% endblock %} {% block opengraph %}{% endblock %} {% block head %}{% endblock %}
</head>

<body>
    {% if guest.extension_is_on({"mod":"cookieconsent"}) %} {% include 'mod_cookieconsent_index.phtml' ignore missing%} {% endif %}

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark shadow fixed-top bg-dark" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{''|link }}">{{company.name}}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainmenu" aria-controls="mainmenu" aria-expanded="false" aria-label="Toggle navigation">
        		<span class="navbar-toggler-icon"></span>
      		</button>

            <div class="collapse navbar-collapse" id="mainmenu">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ 'cart'|link }}" title="{% trans 'Shopping cart' %}"><i class="fa fa-shopping-cart"></i> {% trans 'Shopping cart' %}</a>
                    </li>
                    {% if client %}
					{% set profile = client.client_get %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ ''|link }}" title="{% trans 'Dashboard' %}"><i class="fa fa-home"></i> {% trans 'Dashboard' %}</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="profile-dropdown" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-user"></i> {{ (profile.first_name ~ " " ~ profile.last_name) }}</a>
                        <ul class="dropdown-menu" aria-labelledby="profile-dropdown">
                            <li><a class="dropdown-item" href="{{ 'client/me'|link }}" title="{% trans 'Profile' %}"><i class="fa fa-user-cog fa-fw"></i> {% trans 'Manage profile' %}</a></li>
                            {% if settings.show_client_emails %}
                            <li><a class="dropdown-item" href="{{ 'email'|link }}"><i class="fa fa-envelope fa-fw"></i> {% trans 'Emails'%}</a></li>
							{% endif %}
							{% if settings.show_client_balance %}
                            <li><a class="dropdown-item" href="{{ 'client/balance'|link }}"><i class="fa fa-bank fa-fw"></i> {% trans 'Balance' %}: {{ profile.balance | money(profile.currency) }}</a></li>
							{% endif %}
                            <li><a class="dropdown-item" href="{{ 'client/logout'|link }}" title="{% trans 'Sign out' %}"><i class="fa fa-sign-out-alt fa-fw"></i> {% trans 'Sign out' %}</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a class="nav-link" href="{{ 'login'|link}}">{% trans 'Sign in' %}</a></li>
                    <li><a class="nav-link" href="{{ 'login'|link({'register' : 1}) }}">{% trans 'Register' %}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <!-- /.container -->
    </nav>

    {% block content_banner %}{% endblock %}
    <div class="container">
        <div class="row">

            {% if side_menu == 'hidden' %}
            <div class="col-sm-12">
                {% else %}
                <div class="col-sm-3">
                    {% if company.logo_url %}
                    <h1>
                        <a href="{{ ''|link }}"><img src="{{company.logo_url}}" alt="{{company.name}}" class="mx-auto d-block sidebar-logo" /></a>
                    </h1>
                    {% else %}
                    <h1>
                        <a href="{{ ''|link }}"><img src=" {{ 'images/logo.png' | asset_url }}" alt="{{company.name}}" class="mx-auto d-block sidebar-logo" /></a>
                    </h1>
                    {% endif %}
                    <div class="hidden-xs">{% include "partial_menu.phtml" %}</div>

                    <!--{% set languages = guest.extension_languages %}
					{% if languages|length > 1 %}
					<h2>{% trans 'Select language' %}</h2>
							<select name="lang">
							{% for lang in languages %}
								<option value="{{ lang }}" >{{ lang|trans }}</option>
							{% endfor %}
							</select>
					{% endif %}-->

                    {% block sidebar %}{% endblock %} {% if settings.sidebar_note_enabled %}
                    <div class="well well-sm">
                        <h4>{{ settings.sidebar_note_title }}</h4>
                        <p>{{ settings.sidebar_note_content }}</p>
                    </div>
                    {% endif %} {% block sidebar2 %}{% endblock %}
                </div>
                <div class="col-sm-9">
                    {% endif %} {% block content_before %}{% endblock %} {% include "partial_message.phtml" %} {% block content %}{% endblock %} {% block content_after %}{% endblock %} {% if not client %}
                    <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="{% trans 'Login to client area' %}">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">{% trans 'Login to client area' %}</h4>
                                </div>
                                <div class="modal-body">
                                    <form action="" method="post" class="api_form" data-api-url="{{ 'api/guest/client/login'|link }}" data-api-reload="1">
                                        <div class="control-group form-group">
                                            <div class="controls">
                                                <label>{% trans 'Email address' %}:</label>
                                                <input type="email" class="form-control" name="email" value="{{ request.email }}" required="required" placeholder="{% trans 'Email address' %}">
                                            </div>
                                        </div>
                                        <div class="control-group form-group">
                                            <div class="controls">
                                                <label>{% trans 'Password' %}:</label>
                                                <input type="password" class="form-control" name="password" value="" required="required">
                                            </div>
                                        </div>
                                        <input type="hidden" name="remember" value="1" />
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i></button>
                                            <a class="btn btn-success" href="{{ '/login'|link({'register' : 1}) }}">{% trans 'Create new account' %}</a>
                                            <a class="btn btn-warning" href="{{ 'reset-password'|link }}">{% trans 'Reset password' %}</a>
                                            <input class="btn btn-primary" type="submit" value="{% trans 'Sign in' %}">
                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>

                {% if settings.show_page_footer %}
                <!-- Footer -->
                <hr>
                <footer>
                    <div class="row text-center">
                        <div class="col-lg-12">
                            <p>
                                {% if settings.footer_signature|default %}{{ settings.footer_signature|raw }} {% else %}{{ company.name }} - © {{ now|date('Y') }} {{ company.signature }} {% endif %}
                            </p>
                            <ul class="list-inline">
                                <li><a href="{{ '/about-us'|link }}">{% trans 'About us' %}</a></li>
                                <li><a href="{{ '/tos'|link }}">{% trans 'Terms and Conditions' %}</a></li>
                                <li><a href="{{ '/privacy-policy'|link }}">{% trans 'Privacy Policy' %}</a></li><br /> {% for i in 1..5 %} {% if settings['footer_link_' ~ loop.index ~ '_enabled'] %}
                                <li>
                                    {% if 'http://' in settings['footer_link_' ~ loop.index ~ '_page'] or 'https://' in settings['footer_link_' ~ loop.index ~ '_page'] %}
                                    <a href="{{ settings['footer_link_' ~ loop.index ~ '_page'] }}">{{ settings['footer_link_' ~ loop.index ~ '_title'] }}</a> {% else %}
                                    <a href="{{ settings['footer_link_' ~ loop.index ~ '_page'] | link }}">{{ settings['footer_link_' ~ loop.index ~ '_title'] }}</a> {% endif %}
                                </li>
                                {% endif %} {% endfor %} {% if guest.extension_is_on({"mod":'branding'}) or settings.footer_branding_enabled %}
                                <li><a href="https://github.com/boxbilling/boxbilling" title="Billing Software" target="_blank">{% trans 'Powered by the BoxBilling Community' %}</a></li>
                                {% endif %}
                            </ul>

                        </div>
                        {% if settings.footer_to_top_enabled %}<a href="#top" class="btn btn-default pull-right"><i class="fa fa-arrow-up"></i> {% trans 'Top' %}</a>{% endif %}
                    </div>
                </footer>
                {% endif %}
            </div>
            <!-- /.container -->
            <noscript>NOTE: Many features on BoxBilling require Javascript and cookies. You can enable both via your browser's preference settings.</noscript>
</body>

</html>