{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Payments history' %}{% endblock %}
{% set profile = client.client_get %}

{% block content_before %}
		<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% trans 'Payment history'%}</h1>
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Amount' %}</th>
                    <th>{% trans 'Description' %}</th>
                    <th>{% trans 'Date' %}</th>
                </tr>
            </thead>

            <tbody>
                {% set transactions = client.client_balance_get_list({"per_page":10, "page":request.page}) %}
                {% for i, tx in transactions.list %}
                <tr class="{{ cycle(['odd', 'even'], i) }}">
                    <td>{{ tx.amount | money(tx.currency) }}</td>
                    <td>{{tx.description}}</td>
                    <td>{{tx.created_at|date('Y-m-d h:i')}}</td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="3">{% trans 'The list is empty' %}</td>
                </tr>
                {% endfor %}
            </tbody>

            <tfoot>
                <tr>
                    <th class="currency" colspan="3">{% trans 'Balance' %}: {{ profile.balance | money(profile.currency) }}</th>
                </tr>
            </tfoot>
        </table>
{% include "partial_pagination.phtml" with {'list': transactions} %}

<p class="text-center">
	<a class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#add-funds" aria-expanded="false" aria-controls="add-funds"><i class="fa fa-cart-plus"></i> {% trans 'Add funds' %}</a>
</p>

<div class="collapse card text-center" id="add-funds">

<div class="col">
    <div class="h-100 p-3 bg-light border rounded-3 shadow">
    <form action="" method="post" class="api_form d-inline-block" data-api-url="client/invoice/funds_invoice" data-api-tocreated="{{ 'invoice'|link }}">
        <h5 class="mb-2">{% trans 'Add funds in advance'%}<br /><small>{% trans 'You can add funds to your account if you have active order.' %}</small></h5>
        <hr>
        <div class="input-group mb-2">
            <input type="text" name="amount" class="form-control" aria-describedby="currency-text" required="required"/>
            <span class="input-group-text" id="currency-text">{{ profile.currency }}</span>
		</div>
        <input class="btn btn-success" type="submit" id="add-funds-button" value="{% trans 'Add funds' %}">
    </form>
</div>
</div>
{% endblock %}
