<ol class="breadcrumb">
    {% if selected == 1 %}<li class="breadcrumb-item active text-decoration-none">1. {% trans 'Select product' %}</a></li>
	{% else %}<li class="breadcrumb-item"><a class="text-decoration-none" href="{{ 'order'|link }}">1. {% trans 'Select product' %}</a></li>{% endif %}
	{% if selected == 2 %}<li class="breadcrumb-item active">2. {% trans 'Configure' %} {% if product %} {{ product.title }}{% endif %}</li>
	{% else %}<li class="breadcrumb-item">2. {% trans 'Configure' %}</li>{% endif %}
	<li class="breadcrumb-item {% if selected == 3 %}active{% endif %}">3. {% trans 'Confirm' %}</li>
	<li class="breadcrumb-item {% if selected == 4 %}active{% endif %}">4. {% trans 'Checkout' %}</li>
</ol>