{% if settings.sidebar_note_enabled %}
    <div class="well well-sm">
        <h4>{{ settings.sidebar_note_title }}</h4>
        <p>{{ settings.sidebar_note_content }}</p>
    </div>
{% endif %}	
<div class="list-group">
	{% if settings.side_menu_home %}<a href="{{ ''|link }}" title="{% trans 'Home' %}" class="list-group-item" ><i class="fa fa-home"></i> {% trans 'Home' %}</a>{% endif %}
	{% if settings.side_menu_order %}<a href="{{ '/order'|link }}" title="{% trans 'Order' %}" class="list-group-item{% if request._url starts with '/order/service' %}{% elseif request._url starts with '/order' %} active{% endif %}" ><i class="fa fa-shopping-cart"></i> {% trans 'Order' %}</a>{% endif %}
	{% if settings.side_menu_blog and guest.extension_is_on({"mod":"news"}) %}<a href="{{ '/news'|link }}" title="{% trans 'Blog' %}" class="list-group-item{% if request._url starts with '/news' %} active{% endif %}" ><i class="fa fa-bullhorn"></i> {% trans 'News' %}</a>{% endif %}
	{% if client %}
	<div class="list-group">
		{% if settings.side_menu_services %}<a href="{{ 'order/service'|link }}" title="{% trans 'Services' %}" class="list-group-item{% if request._url starts with '/order/service' %} active{% endif %}"><span style="color: #0ce3ac;"><i class="fa fa-cog"></i> {% trans 'Services' %}</span></a>{% endif %}
		{% if settings.side_menu_invoices %}<a href="{{ 'invoice'|link }}" title="{% trans 'Invoices' %}" class="list-group-item{% if request._url starts with '/invoice' %} active{% endif %}"><span style="color: #0ce3ac;"><i class="fa fa-credit-card"></i> {% trans 'Invoices' %}</span></a>{% endif %}
		{% if settings.show_page_footer %}
			{% for i in 1..5 %}
				{% if settings['sidebar_button_' ~ loop.index ~ '_enabled'] %}
						{% if 'http://' in settings['sidebar_button_' ~ loop.index ~ '_page'] or  'https://' in settings['sidebar_button_' ~ loop.index ~ '_page'] %}
							<a href="{{ settings['sidebar_button_' ~ loop.index ~ '_page'] }}" class="list-group-item"><span style="color: #0ce3ac;"><i class="fa {{ settings['sidebar_button_' ~ loop.index ~ '_icon'] }}"></i> {{ settings['sidebar_button_' ~ loop.index ~ '_title'] }}</a>
						{% else %}
						    <a href="{{ settings['sidebar_button_' ~ loop.index ~ '_page'] }}" class="list-group-item"><span style="color: #0ce3ac;"><i class="fa {{ settings['sidebar_button_' ~ loop.index ~ '_icon'] }}"></i> {{ settings['sidebar_button_' ~ loop.index ~ '_title'] }}</a>
						{% endif %}
				{% endif %}
			{% endfor %}
	{% endif %}
		<!--<a href="{{ '/client/balance'|link }}" title="{% trans 'Payment history' %}" class="list-group-item{% if request._url starts with '/client/balance' %} active{% endif %}" ><span style="color: #0ce3ac;"><i class="fa fa-archive"></i> {% trans 'Payment history' %}</span></a>-->
	</div>
{% else %}
		{% if settings.side_menu_register %}<a href="{{ '/login'|link }}" title="{% trans 'Sign in / Register' %}" class="list-group-item list-group-item-success" >{% trans 'Sign in / Register' %}</a>{% endif %}
{% endif %}
</div>
