name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: ./src

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ./src/bb-vendor
        key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-    

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./src

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: |
        cp ./src/bb-config-sample.php ./src/bb-config.php
        mkdir ./src/bb-data/cache
        touch ./src/bb-data/log/license.log
        touch ./src/bb-data/log/php_error.log
        touch ./src/bb-data/log/application.log        
        php ./src/bb-vendor/bin/phpunit ./tests/bb-modules/
